# Generated by Django 5.2.6 on 2025-09-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
