# Generated by Django 5.2.6 on 2025-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ghost_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
