# Generated by Django 5.2.5 on 2025-10-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_duration_game_ghost_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
    ]
